SET SERVEROUTPUT ON

DECLARE
V_CONTADOR NUMBER(10):=1;
V_FIM V_CONTADOR%TYPE:=&QTD;

BEGIN
LOOP
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
    V_CONTADOR:= V_CONTADOR +1;
    EXIT WHEN V_CONTADOR > V_FIM;
    END LOOP;
END;
/

DECLARE 
V_NOME ALUNO.NOME%TYPE;
V_RM ALUNO.RM%TYPE;

CURSOR C_ALUNO IS
SELECT RM,NOME FROM ALUNO; -- CURSOR CRIA COMO SE FOSSE UM ARRAY COM O RM DE TODOS OS ALUNOS PARA ESSE CONDIÇÃO (PESQUISAR MAIS SOBRE)

BEGIN
    FOR ALUNO IN C_ALUNO LOOP -- ESSE FOR SELECIONA OS DADOS INDIVIDUAIS DO ALUNO PARA JOGAR NA SEGUINTE VARIÁVEL
   -- V_RM := ALUNO.RM;
       -- SELECT NOME INTO V_NOME FROM ALUNO WHERE RM = V_RM; -- SELECT MAIS LONGO
        DBMS_OUTPUT.PUT_LINE('NOME DO ALUNO: ' ||ALUNO.NOME); -- VERSÃO SIMPLIFICADA
    END LOOP;
END;
/

--V_QTD_ALUNO NUMBER(10);
--SELECT COUNT(*) INTO V_QTD_ALUNO FROM ALUNO; SINTAXE PARA SABER O 'LENGTH' DA TABELA

SELECT * FROM ALUNO;

