SET SERVEROUTPUT ON

DECLARE
V_CONTADOR NUMBER(10):=1;
V_FIM V_CONTADOR%TYPE:=&QTD;

BEGIN
LOOP
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
    V_CONTADOR:= V_CONTADOR +1;
    EXIT WHEN V_CONTADOR > V_FIM;
    END LOOP;
END;
/
